### ISSUE TITLE
M1 build ? 

### ISSUE THREAD

**Issue by Pdaa** [mrRay/jit.gl.isf#7]
would it be possible to build jit.gl.isf for the  M1 ?

**Comment by Pdaa** [comment]
Any plans on a future update to make this posible ?

**Comment by Pdaa** [comment]
Any plans on a future update to make this posible?

**Comment by jaaaamIron** [comment]
I was also going to ask about this. Would it not just be a case of compiling it for the new architecture in XCode? I'm aware it might not be so simple!

**Comment by robtherich** [comment]
M1 build went live Nov 2022. Development is now on this branch - https://github.com/mrRay/jit.gl.isf/tree/m1-cmake
