### ISSUE TITLE
Errors in the audioreactive example patches

### ISSUE THREAD

**Issue by jaaaamIron** [mrRay/jit.gl.isf#8]
Hi. When I run the Audio Reactive examples accesed through max help I get error messages:
jit.gl.isf: ERR: unrecognized param "fftImage"
jit.gl.isf: ERR: unrecognized param "waveImage"

Has anyone tested these as working recently?

I'm using Max 8.5.6

**Comment by jaaaamIron** [comment]
Just updating this:
I can confirm that there are numerous patching errors in the AudioReactive examples.
For example:
FFT color lines needs the waveImage param to be disabled

Radial Spectrogram doesn't work at all.

Does anyone know a fix?

**Comment by robtherich** [comment]
These are just patching issues. edit the patch as needed for your use cases.
